import numpy as np
print("Name: Aparna Jayakumar")
print("Reg no: SJC22MCA-2012")
print("course: Data Science Lab")
print("coursecode: 20MCA241")
print("Date: 10-10-23")
print("unintialized array")
uninitialized_array =np.empty=(3,2)
print(uninitialized_array)
print("array with element one")
array=np.full((3,2),1)
print(array)
print("array with element zero")
arr=np.full((3,2),0)
print(arr)
